# Site
repository: jteano/jteano.github.io
#favicon: images/favicon.ico

# Personal info
name: John Teano
title: Junior Developer
email: teano.john@gmail.com
website: www.johnteano.me

# Social links
#twitter_username: facespics
github_username:  jteano
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: john-teano-1963811b4/
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is John and I currently work as an IT Technician. I'm currently pursuing my Bachelor's Degree in Computer Science at California State University of Long Beach. I've worked on coding projects here and there to achieve my goal of being a software engineer. 
  
  I am most skilled in: <mark>Information Technology</mark> and <mark>Software Management</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Cooking
   - Surfing
   - Tinkering with Electronics

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
